- name: Wait for kube-apiserver to be ready on port 6443
  wait_for:
    port: 6443
    host: 127.0.0.1
    timeout: 90
    state: started

- name: Install kube-proxy manually (first)
  shell: kubeadm init phase addon kube-proxy
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: kube_proxy_result
  retries: 3
  delay: 5
  until: kube_proxy_result.rc == 0

- name: Apply Flannel CNI manifest
  shell: KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply --validate=false -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  register: flannel_result
  until: flannel_result.rc == 0
  retries: 10
  delay: 10

- name: Wait for flannel daemonset to be ready
  shell: |
    kubectl rollout status daemonset/kube-flannel-ds -n kube-flannel
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: rollout_flannel
  retries: 10
  delay: 5
  until: rollout_flannel.rc == 0

- name: Remove master taints to allow pod scheduling
  shell: |
    kubectl taint nodes --all node-role.kubernetes.io/master- || true
    kubectl taint nodes --all node-role.kubernetes.io/control-plane:NoSchedule- || true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
