---
- name: Manage Private Instances via SSM
  hosts: app_servers  # 또는 프라이빗 인스턴스들의 그룹명
  gather_facts: yes
  become: yes

  pre_tasks:
    - name: Test SSM connectivity
      ping:

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install required packages
      apt:
        name:
          - curl
          - wget
          - unzip
          - htop
        state: present

    - name: Create application directory
      file:
        path: /opt/myapp
        state: directory
        mode: '0755'

    - name: Check system information
      debug:
        msg: 
          - "Hostname: {{ inventory_hostname }}"
          - "Private IP: {{ ansible_default_ipv4.address }}"
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"