package com.ssafy.domain.model.measure

data class CompositionDetailItem(
    val bmr: Double,
    val bodyAge: Int,
    val compositionLogId: Int,
    val createdAt: String,
    val ecw: Double,
    val icw: Double,
    val memberId: Int,
    val mineral: Double,
    val protein: Double,
    val smm: Double,
    val bfp: Double,
    val bfm: Double,
    val weight: Double,
    val weightLabel: String,
    val weightCount: Int,
    val bfmLabel: String,
    val bfmCount: Int,
    val bfpLabel: String,
    val bfpCount: Int,
    val smmLabel: String,
    val smmCount: Int,
    val bmiLabel: String,
    val bmiCount: Int,
    val tcwLabel: String,
    val tcwCount: Int,
    val proteinLabel: String,
    val proteinCount: Int,
    val mineralLabel: String,
    val mineralCount: Int,
    val ecwRatioLabel: String,
    val ecwRatioCount: Int
)
