server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fitpt?serverTimezone=Asia/Seoul
    username: root
    password: ssafy

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false

logging:
  level:
    com.board: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  swagger-ui:
    tags-sorter: alpha # 알파벳순
    operations-sorter: alpha
  packages-to-scan: com.board.jamesboard
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
